server {
    listen 80;
    server_name guardamarhotelspa.com www.guardamarhotelspa.com;

    root /var/www/Quademar/site/dist;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}